---
- name: check if razor is already installed
  stat:
    path: /usr/bin/razor-admin
  register: razor_installed

- name: ensure razor is installed
  apt:
    pkg: razor
    state: present

- name: ensure razor creates home after install
  command: "{{ item }}"
  args:
    creates: "{{ spamassassin_razor_config_dir }}"
  with_items:
    - "razor-admin -home={{ spamassassin_razor_config_dir }} -create"
  when: razor_installed.stat.exists == false
  notify: restart spamassassin

- name: ensure razor registers identity after install
  command: "razor-admin -home={{ spamassassin_razor_config_dir }} -register"
  when: razor_installed.stat.exists == false
  notify: restart spamassassin

- name: ensure razor discovers home after install
  command: "razor-admin -home={{ spamassassin_razor_config_dir }} -discover"
  when: razor_installed.stat.exists == false
  notify: restart spamassassin
